### ISSUE TITLE
Wonderful work. May I ask when will the detail code to be released.

### ISSUE THREAD

**Issue by yangrongkun** [junshengzhou/DeepPriorAssembly#1]

**Comment by junshengzhou** [comment]
Thanks for your attention! We are preparing the code. I believe it will be ready within a month.

**Comment by SionHu** [comment]
Congratulations for the paper! Would love to checkout the code and some pre-trained model as well 👀

**Comment by junshengzhou** [comment]
The code is released. I will close the issue.
